### ISSUE TITLE
CustomQuery parameters problem

### ISSUE THREAD

**Issue by turowicz** [MiracleDevs/Paradigm.ORM#5]
Hey gang @pabloordonez @lbrugnara @bgrainger

I get the following error when trying to use CustomQuery and params.
```
There was a problem executing the command.
Paradigm.ORM.Data.Exceptions.DatabaseCommandException: There was a problem executing the command.
 ---> Cassandra.SyntaxError: line 1:46 no viable alternative at input 'rowkey' (...FROM unitdata WHERE partitionkey = [?] rowkey...)
   at Cassandra.Requests.PrepareHandler.SendRequestToOneNode(IInternalSession session, IEnumerator`1 queryPlan, PrepareRequest request)
   at Cassandra.Requests.PrepareHandler.Prepare(PrepareRequest request, IInternalSession session, IEnumerator`1 queryPlan)
   at Cassandra.Cluster.Cassandra.SessionManagement.IInternalCluster.Prepare(IInternalSession session, ISerializerManager serializerManager, PrepareRequest request)
   at Cassandra.Session.PrepareAsync(String cqlQuery, String keyspace, IDictionary`2 customPayload)
   at Cassandra.Tasks.TaskHelper.WaitToComplete(Task task, Int32 timeout)
   at Cassandra.Session.Prepare(String cqlQuery, String keyspace, IDictionary`2 customPayload)
   at Cassandra.Data.CqlCommand.Prepare()
   at Cassandra.Data.CqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Paradigm.ORM.Data.Cassandra.CqlDatabaseCommand.ExecuteReaderAsync()
   --- End of inner exception stack trace ---
   at Paradigm.ORM.Data.Cassandra.CqlDatabaseCommand.ExecuteReaderAsync()
   at Paradigm.ORM.Data.Extensions.DatabaseConnectorExtensions.ExecuteReaderAsync[T](IDatabaseConnector connector, IDatabaseCommand command, Func`2 action)
   at Paradigm.ORM.Data.Querying.CustomQuery`1.ExecuteAsync(String whereClause, Object[] parameters)
```

My code:

```c#
using (var context = await _contextFactory())
{
    var query = new CustomQuery<TDb>(context, $"SELECT * FROM {GetTable<TEntity>()}");
    var where = new StringBuilder();
    var parameters = new List<object>();

    parameters.Add(partitionKey);
    where.Append($"{ColumnPartition} = @{parameters.Count}");

    if (!string.IsNullOrWhiteSpace(startRowKey))
    {
        parameters.Add(startRowKey);
        where.Append($"AND {ColumnRow} >= @{parameters.Count}");
    }

    if (!string.IsNullOrWhiteSpace(endRowKey))
    {
        parameters.Add(endRowKey);
        where.Append($"AND {ColumnRow} <= @{parameters.Count}");
    }

    var results = await query.ExecuteAsync(where.ToString(), parameters.ToArray()); // exception here

    return _mapper.MapFromDb<TEntity, TDb>(results);
}
```

Any ideas how can I solve this problem?

**Comment by turowicz** [comment]
Solved by adding a whitespace to the end of each where.Append
